### ISSUE TITLE
Returns schedules without off in periods 4||5||6

### ISSUE THREAD

**Issue by matthewa313** [Coreball/ScheduleStacker#1]
Students are required to have an off period for a lunch in period four, five, or six.  However, the program occasionally returns schedules that do not have a lunch period.

Lunch period depends on grade:
Freshmen & Sophomores -- periods 4/6
Juniors & Seniors -- periods 5

Possible solution: Grade JList in the form determines required lunch period(s) -> if(a required lunch period is off) -> add finished schedule

Version: latest

**Comment by Coreball** [comment]
Currently lunch periods are treated as as normal desired off periods (check the box for it and stuff), since having a grade selector would make it more complicated (in my opinion) and would not give sophomores/freshmen the option of searching for one lunch period only, having to search for both periods 4/6 which increases resource usage unnecessarily if they are going to immediately discard half of them. Forcing the user to input their grade would make generation control less granular and at the moment I do not see any purpose for it other than determining which lunch periods the user is obligated to have. Hopefully people realize they need a lunch period, in the usage tutorial I use the example of period 5 + another off. If they do indeed opt not to select the standard lunch periods it could be do to unique circumstances that would be harder to account for in the grade-list model.
